name: Github Actions Demo
run-name: ${{ github.actor }} is testing out Github Actions
on: [push]

jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - run: ls -la
      - run: pwd
      - run: echo "::notice title=My Title::This is a notice"
      - run: echo "::error title=My Error::This is an error"

      - name: Checkout repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runnder."

      - name: List files in the repository
        run: ls -la

      - name: List files in the repository
        run: ls -la
